swagger: '2.0'
info:
  title: 'Node JS assignment'

paths:
  # Create a post
  /post/create:
    post:
      summary: Create a post
      produces:
        - application/json
      consumes:
        - application/json
      parameters:
        - in: body
          name: body
          schema:
            $ref: '#/components/schemas/POST'
      responses:
        200: # SUCCESS
          description: Date inserted successfully
          schema:
            type: object
            properties:
              success:
                type: boolean
              data:
                type: object
                properties:
                  id:
                    type: integer
                  name:
                    type: string
                  cost:
                    type: number
                  description:
                    type: string
              message:
                default: 'Date inserted successfully'
              status:
                default: 200
        400: # BAD REQUEST
          description: Bad Request
          schema:
            type: object
            properties:
              success:
                type: boolean
              message:
                type: string
                default: 'Bad Request'
              status:
                type: integer
                default: 500
              data:
                type: object
        500: # FAIL
          description: Internal Server Error
          schema:
            type: object
            properties:
              success:
                type: boolean
              message:
                type: string
                default: 'Internal Server Error'
              status:
                type: integer
                default: 500
              data:
                type: object

  # Returns all Posts
  /post/get:
    get:
      summary: Returns all Posts
      responses:
        200: # SUCCESS
          description: Data fetched successfully
          schema:
            type: object
            properties:
              success:
                type: boolean
              data:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: integer
                    name:
                      type: string
                    cost:
                      type: number
                    description:
                      type: string
              message:
                default: 'Data fetched successfully'
              status:
                default: 200
        500: # FAIL
          description: Internal Server Error
          schema:
            type: object
            properties:
              success:
                type: boolean
              message:
                type: string
                default: 'Internal Server Error'
              status:
                type: integer
                default: 500
              data:
                type: array

  # Update cost of a post
  /post/update/{id}:
    put:
      summary: Update cost of a post
      produces:
        - application/json
      consumes:
        - application/json
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
            format: int64
        - in: body
          name: body
          schema:
            $ref: '#/components/schemas/UPDATE'
      responses:
        200: # SUCCESS
          description: Data updated successfully
          schema:
            type: object
            properties:
              success:
                type: boolean
              message:
                type: string
                default: 'Data fetched successfully'
              status:
                type: integer
                default: 200
        400: # BAD REQUEST
          description: Bad Request
          schema:
            type: object
            properties:
              success:
                type: boolean
              message:
                type: string
                default: 'Bad Request'
              status:
                type: integer
                default: 500
        404: # Record not found
          description: Record not found
          schema:
            type: object
            properties:
              success:
                type: boolean
              message:
                type: string
                default: 'No record found to update'
              status:
                type: integer
                default: 404
        500: # FAIL
          description: Internal Server Error
          schema:
            type: object
            properties:
              success:
                type: boolean
              message:
                type: string
                default: 'Internal Server Error'
              status:
                type: integer
                default: 500

  # Delete a post
  /post/delete/{id}:
    delete:
      summary: Delete a post
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int64
      responses:
        200: # SUCCESS
          description: Data deleted successfully
          schema:
            type: object
            properties:
              success:
                type: boolean
              message:
                type: string
                default: 'Data deleted successfully'
              status:
                type: integer
                default: 200
        404: # Record not found
          description: Record not found
          schema:
            type: object
            properties:
              success:
                type: boolean
              message:
                type: string
                default: 'No record found to delete'
              status:
                type: integer
                default: 404
        500: # FAIL
          description: Internal Server Error
          schema:
            type: object
            properties:
              success:
                type: boolean
              message:
                type: string
                default: 'Internal Server Error'
              status:
                type: integer
                default: 500

# Defining SCHEMAS for POST/PUT
components:
  schemas:
    POST:
      type: object
      required:
        - name
        - cost
        - description
      properties:
        name:
          type: string
        cost:
          type: number
        description:
          type: string

    UPDATE:
      type: object
      required:
        - cost
      properties:
        cost:
          type: number